# Generated by Django 2.1 on 2018-11-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_ajustada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dQ', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('SSm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ETR', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Delta_ssm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('SUZ2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Perc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Delta_Suz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('SIz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q0', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Delta_Suz_prima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Q_gen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Caudal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Delta_SIz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Etp', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'etp_tb',
            },
        ),
        migrations.CreateModel(
            name='Pcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Pcp', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'pcp_tb',
            },
        ),
        migrations.CreateModel(
            name='UnidadHidrologica',
            fields=[
                ('Id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Hd_Area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Hd_Msnm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_Ssm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_Suz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_SIz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_UZL0', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_UZL1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Cs_UZL2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_Pcorr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_Pcalt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_FC', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_LP', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_Beta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Bh_Cflux', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Hes_K0', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Hes_K1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Hes_K2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Hes_K3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('HeI_K4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('HeI_PERC', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('HeI_MAXBIAS', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pcp',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.UnidadHidrologica'),
        ),
        migrations.AddField(
            model_name='etp',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.UnidadHidrologica'),
        ),
        migrations.AddField(
            model_name='calculomodelo',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.UnidadHidrologica'),
        ),
    ]
